-- Describe RESERVATIONS
CREATE TABLE RESERVATIONS (
    "OWNER_USER_NAME" VARCHAR(84),
    "LOCATION" VARCHAR(250),
    "DATE_OF_RESERVATION" DATE,
    "NUMBER_OF_NIGHTS" INT,
    "UNIT_SIZE" VARCHAR(200),
    "CONFIRMATION_NUMBER" TEXT,
    "POINTS_REQUIRED_FOR_RESERVATION" INT,
    "WAS_DISCOUNTED" BOOLEAN(1),
    "WAS_UPGRADED" BOOLEAN(1),
    "IS_BUYER_LINED_UP" BOOLEAN(1),
    "GUEST_EMAIL" VARCHAR(84),
    "AMOUNT_PAID" DOUBLE PRECISION,
    "PAYMENT_METHOD" VARCHAR(100),
    "TOTAL_RENTING_FOR" DOUBLE PRECISION,
    "DATE_BOOKED" TEXT
)