CREATE TABLE OWNERS
(
	EMAIL VARCHAR(89) not null ,
	FIRST_NAME VARCHAR(35) not null,
	LAST_NAME VARCHAR(35) not null,
	PHONE_NUMBER VARCHAR(16),
	USER_NAME VARCHAR(200) primary key,
	PASSWORD VARCHAR(200),
	POINTS_OWNED INT,
	CURRENT_POINTS INT,
	OWNER_REIMBURSEMENT_RATE DOUBLE PRECISION
)