/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacationscheduler;

import Connections.RuthDBConnection;
import dao.GuestFactory;
import dataobjs.Guest;
import javax.swing.JFrame;

/**
 *
 * @author erikbenscoter
 */
public class GuestMaitenanceForm extends javax.swing.JPanel {

    /**
     * Creates new form GuestMaitenanceForm
     */
    
    boolean isUpdate = false;
    UsersTab  userTab;

    ReservationForm rf;
    JFrame jf;
    public GuestMaitenanceForm(UsersTab userTab){
        this.userTab = userTab;
        commonConstructor();
    }
    public GuestMaitenanceForm() {
       commonConstructor();
        
    }
    public GuestMaitenanceForm(String emailAddress){
        commonConstructor();
        Guest appropriateGuest = GuestFactory.getGuests(emailAddress);
        System.err.println("\n");
        appropriateGuest.print();
        TextPane_FirstName.setText(appropriateGuest.getFirstName());
        TextPane_LastName.setText(appropriateGuest.getLastName());
        TextPane_Email.setText(appropriateGuest.getEmailAddress());
        TextPane_CreditCardNumber.setText( appropriateGuest.getCreditCardNumber() );
        TextPane_PhoneNumber.setText(appropriateGuest.getPhoneNumber());
        TextPane_PreviousRentals.setText(Integer.toString(appropriateGuest.getNumberPreviousRentals()));
        
        isUpdate = true;
        
    }
    public void commonConstructor(){
        initComponents();
    }
    
    public void setJf(JFrame jf) {
        this.jf = jf;
    }

    public void setRf(ReservationForm rf) {
        this.rf = rf;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPane_Email = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextPane_PhoneNumber = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextPane_LastName = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextPane_FirstName = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextPane_CreditCardNumber = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextPane_PreviousRentals = new javax.swing.JTextPane();
        Button_okay = new javax.swing.JButton();
        Button_Cancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Email");

        jLabel4.setText("Phone Number");

        jLabel5.setText("Credit Card Number");

        jScrollPane1.setViewportView(TextPane_Email);

        jLabel6.setText("Previous Rentals");

        jScrollPane2.setViewportView(TextPane_PhoneNumber);

        jScrollPane3.setViewportView(TextPane_LastName);

        jScrollPane4.setViewportView(TextPane_FirstName);

        jScrollPane5.setViewportView(TextPane_CreditCardNumber);

        jScrollPane6.setViewportView(TextPane_PreviousRentals);

        Button_okay.setBackground(new java.awt.Color(81, 255, 0));
        Button_okay.setText("Apply");
        Button_okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_okayActionPerformed(evt);
            }
        });

        Button_Cancel.setBackground(new java.awt.Color(255, 5, 0));
        Button_Cancel.setText("Cancel");
        Button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_okay)
                .addGap(18, 18, 18)
                .addComponent(Button_Cancel)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_okay)
                    .addComponent(Button_Cancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_okayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_okayActionPerformed
        String ccn = this.TextPane_CreditCardNumber.getText();
        String email = this.TextPane_Email.getText();
        String first = this.TextPane_FirstName.getText();
        String last = this.TextPane_LastName.getText();
        String phoneNumber = this.TextPane_PhoneNumber.getText();
        int prev = Integer.parseInt(this.TextPane_PreviousRentals.getText());
        
        Guest g = new Guest(email, first, last, phoneNumber, ccn, prev);
        if(!isUpdate){
            GuestFactory.insert(g);
        }else{
            GuestFactory.update(g);
        }
        if(userTab != null){
            userTab.resetPanel();
        }
        if(rf != null){
            rf.refresh();
        }
        if(jf != null){
            jf.dispose();
        }
        
        
    }//GEN-LAST:event_Button_okayActionPerformed

    private void Button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelActionPerformed
       if(userTab != null){
            userTab.resetPanel();
       }
       if(rf != null){
           rf.refresh();
       }
       if(jf != null){
           jf.dispose();
       }
       
    }//GEN-LAST:event_Button_CancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cancel;
    private javax.swing.JButton Button_okay;
    private javax.swing.JTextPane TextPane_CreditCardNumber;
    private javax.swing.JTextPane TextPane_Email;
    private javax.swing.JTextPane TextPane_FirstName;
    private javax.swing.JTextPane TextPane_LastName;
    private javax.swing.JTextPane TextPane_PhoneNumber;
    private javax.swing.JTextPane TextPane_PreviousRentals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
