/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacationscheduler;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.JComponent;
import static vacationscheduler.UsersTab.OwnerOrGuest.GUEST;
import static vacationscheduler.UsersTab.OwnerOrGuest.OWNER;

/**
 *
 * @author erikbenscoter
 */
public class Home extends javax.swing.JFrame {
    private static Object tabbedPane;

    /**
     * Creates new form Home
     */
    int numberOfTabs=3;
    public Home() {
        initComponents();
        createTabs();
        this.jTabbedPane1.setBackground(Color.white);
        for(int i = 0;i<numberOfTabs; i++){
            Color colors[] = {Color.LIGHT_GRAY,Color.GREEN,
                                Color.PINK,Color.WHITE,Color.YELLOW};
            Random r = new Random();
            int x = r.nextInt(colors.length);
            System.out.println(x);
            
            this.jTabbedPane1.setBackgroundAt(i, colors[x]);
        }
        this.jTabbedPane1.setBackgroundAt(WIDTH, Color.yellow);
       
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
        
        
        
        
    }
    private void createTabs(){
        //tab 0 is home
            jTabbedPane1.addTab("Home", new UpcomingReservations());
            jTabbedPane1.setMnemonicAt(0, KeyEvent.VK_1);
            this.setVisible(true);
        //tab 1 will be owners
            this.jTabbedPane1.addTab("Owners", new UsersTab(OWNER));
            jTabbedPane1.setMnemonicAt(1, KeyEvent.VK_1);
            this.setVisible(true);
        //tab 2 will be guests
            this.jTabbedPane1.addTab("Guests", new UsersTab(GUEST));
            jTabbedPane1.setMnemonicAt(2, KeyEvent.VK_1);
            this.setVisible(true);
        //tab 3 will be reservations
            this.jTabbedPane1.addTab("Reservation", new ReservationsTab());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
