/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacationscheduler;

import Connections.RuthDBConnection;
import dao.OwnersFactory;
import javax.swing.JFrame;

/**
 *
 * @author erikbenscoter
 */
public class OwnerMaitenanceForm extends javax.swing.JPanel {

    /**
     * Creates new form MakeNewUser
     */
    Owner own;
    UsersTab userTab;
    public OwnerMaitenanceForm(UsersTab userTab){
        this.userTab = userTab;
        InCommonConstructor();
    }
    public OwnerMaitenanceForm() {
        InCommonConstructor();
    }
    public void InCommonConstructor(){
        initComponents();
        
        this.setVisible(true);
        own = new Owner();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_FirstName = new javax.swing.JLabel();
        TextField_FirstName = new javax.swing.JTextField();
        Label_LastName = new javax.swing.JLabel();
        TextField_LastName = new javax.swing.JTextField();
        Label_PointsOwned = new javax.swing.JLabel();
        TextField_PointsOwned = new javax.swing.JTextField();
        Label_OwnerReimburseRate = new javax.swing.JLabel();
        TextField_OwnerReimburseRate = new javax.swing.JTextField();
        Button_Okay = new javax.swing.JButton();
        Button_Cancel = new javax.swing.JButton();
        Label_Email = new javax.swing.JLabel();
        Label_PhoneNumber = new javax.swing.JLabel();
        Label_Password = new javax.swing.JLabel();
        TextField_Email = new javax.swing.JTextField();
        TextField_PhoneNumber = new javax.swing.JTextField();
        TextField_Password = new javax.swing.JTextField();
        TextField_UserName = new javax.swing.JTextField();
        Label_UserName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Label_FirstName.setText("First Name:");

        TextField_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_FirstNameActionPerformed(evt);
            }
        });

        Label_LastName.setText("Last Name:");

        TextField_LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_LastNameActionPerformed(evt);
            }
        });

        Label_PointsOwned.setText("Points Owned");

        TextField_PointsOwned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_PointsOwnedActionPerformed(evt);
            }
        });

        Label_OwnerReimburseRate.setText("Owner Reimbursement Rate:");

        Button_Okay.setBackground(new java.awt.Color(0, 255, 0));
        Button_Okay.setText("Okay");
        Button_Okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_OkayActionPerformed(evt);
            }
        });

        Button_Cancel.setBackground(new java.awt.Color(255, 0, 46));
        Button_Cancel.setText("Cancel");
        Button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelActionPerformed(evt);
            }
        });

        Label_Email.setText("Email:");

        Label_PhoneNumber.setText("Phone Number:");

        Label_Password.setText("Password:");

        TextField_PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_PhoneNumberActionPerformed(evt);
            }
        });

        Label_UserName.setText("User Name:");

        jLabel1.setText("x-(xxx)-xxx-xxxx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Button_Okay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Cancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Label_PhoneNumber)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextField_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label_Email)
                                        .addGap(171, 171, 171)
                                        .addComponent(TextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(0, 134, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_OwnerReimburseRate)
                            .addComponent(Label_LastName)
                            .addComponent(Label_FirstName)
                            .addComponent(Label_PointsOwned)
                            .addComponent(Label_Password)
                            .addComponent(Label_UserName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_OwnerReimburseRate, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TextField_UserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                        .addComponent(TextField_Password, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(TextField_PointsOwned, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_FirstName)
                    .addComponent(TextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_LastName)
                    .addComponent(TextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Email)
                    .addComponent(TextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextField_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(Label_PhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_UserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_UserName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Password)
                    .addComponent(TextField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_PointsOwned)
                    .addComponent(TextField_PointsOwned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_OwnerReimburseRate)
                    .addComponent(TextField_OwnerReimburseRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Okay)
                    .addComponent(Button_Cancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_FirstNameActionPerformed

    private void TextField_PointsOwnedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_PointsOwnedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_PointsOwnedActionPerformed

    private void Button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelActionPerformed
        this.userTab.resetPanel();
    }//GEN-LAST:event_Button_CancelActionPerformed

    private void TextField_PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_PhoneNumberActionPerformed

    private void Button_OkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_OkayActionPerformed
        own.emailAddress = this.TextField_Email.getText();
        own.firstName = this.TextField_FirstName.getText();
        own.lastName = this.TextField_LastName.getText();
        own.password = this.TextField_Password.getText();
        own.phoneNumber = this.TextField_PhoneNumber.getText();
        own.pointsOwned = Integer.parseInt(this.TextField_PointsOwned.getText());
        own.reimbursementRate = Double.parseDouble(this.TextField_OwnerReimburseRate.getText());
        own.userName = this.TextField_UserName.getText();
        
 //       DBConnection dbconnection = new DBConnection();
        OwnersFactory.insert(own);
        this.userTab.resetPanel();
        
        
    }//GEN-LAST:event_Button_OkayActionPerformed

    private void TextField_LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_LastNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cancel;
    private javax.swing.JButton Button_Okay;
    private javax.swing.JLabel Label_Email;
    private javax.swing.JLabel Label_FirstName;
    private javax.swing.JLabel Label_LastName;
    private javax.swing.JLabel Label_OwnerReimburseRate;
    private javax.swing.JLabel Label_Password;
    private javax.swing.JLabel Label_PhoneNumber;
    private javax.swing.JLabel Label_PointsOwned;
    private javax.swing.JLabel Label_UserName;
    private javax.swing.JTextField TextField_Email;
    private javax.swing.JTextField TextField_FirstName;
    private javax.swing.JTextField TextField_LastName;
    private javax.swing.JTextField TextField_OwnerReimburseRate;
    private javax.swing.JTextField TextField_Password;
    private javax.swing.JTextField TextField_PhoneNumber;
    private javax.swing.JTextField TextField_PointsOwned;
    private javax.swing.JTextField TextField_UserName;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
