/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacationscheduler;

/**
 *
 * @author erikbenscoter
 */
public class ReservationForm extends javax.swing.JPanel {

    /**
     * Creates new form ReservationForm
     */
    public ReservationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBox_User = new javax.swing.JComboBox();
        Label_User = new javax.swing.JLabel();
        Label_PointsAvailable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Label_ReservationDate = new javax.swing.JLabel();
        TextBox_DateOfReservation = new javax.swing.JTextField();
        Label_UseDate = new javax.swing.JLabel();
        TextBox_UseDate = new javax.swing.JTextField();
        Label_NumberOfNights = new javax.swing.JLabel();
        TextBox_NumberOfNights = new javax.swing.JTextField();
        Label_UnitSize = new javax.swing.JLabel();
        ComboBox_UnitSize = new javax.swing.JComboBox();
        Label_ConfirmationNumber = new javax.swing.JLabel();
        TextBox_ConfirmationNumber = new javax.swing.JTextField();
        Label_PointsRequired = new javax.swing.JLabel();
        TextBox_PointsRequired = new javax.swing.JTextField();
        Label_PointsAfter = new javax.swing.JLabel();
        Label_CalculatedPointsAfter = new javax.swing.JLabel();
        Label_Discounted = new javax.swing.JLabel();
        Checkbox_Discounted = new javax.swing.JCheckBox();
        Label_Upgraded = new javax.swing.JLabel();
        Checkbox_upgraded = new javax.swing.JCheckBox();
        Label_GuestOrHolding = new javax.swing.JLabel();
        Radiobtn_Guest = new javax.swing.JRadioButton();
        Radiobtn_Holding = new javax.swing.JRadioButton();
        Label_GuestName = new javax.swing.JLabel();
        TextBox_GuestName = new javax.swing.JTextField();
        Label_AmountPaid = new javax.swing.JLabel();
        TextBox_AmountPaid = new javax.swing.JTextField();
        Label_DatePaid = new javax.swing.JLabel();
        TextBox_DatePaid = new javax.swing.JTextField();
        Label_PaymentMethod = new javax.swing.JLabel();
        Radiobtn_Cash = new javax.swing.JRadioButton();
        Radiobtn_Credit = new javax.swing.JRadioButton();
        Radiobtn_Other = new javax.swing.JRadioButton();
        TextBox_OtherPaymentMethod = new javax.swing.JTextField();
        Btn_Okay = new javax.swing.JButton();
        Btn_Cancel = new javax.swing.JButton();

        ComboBox_User.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Label_User.setText("User");

        Label_PointsAvailable.setText("Available Points:");

        jLabel3.setText("jLabel3");

        Label_ReservationDate.setText("Date of Reservation:");

        TextBox_DateOfReservation.setText("jTextField1");

        Label_UseDate.setText("Use Date:");

        TextBox_UseDate.setText("jTextField2");

        Label_NumberOfNights.setText("Number of Nights:");

        TextBox_NumberOfNights.setText("0");

        Label_UnitSize.setText("Unit Size:");

        ComboBox_UnitSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Label_ConfirmationNumber.setText("Confirmation #:");

        TextBox_ConfirmationNumber.setText(" ");

        Label_PointsRequired.setText("Points Required:");

        TextBox_PointsRequired.setText("0");

        Label_PointsAfter.setText("Points After:");

        Label_CalculatedPointsAfter.setText("jLabel11");

        Label_Discounted.setText("Was It Discounted:");

        Checkbox_Discounted.setText("check if discounted");

        Label_Upgraded.setText("Was it upgraded?:");

        Checkbox_upgraded.setText("check if upgraded");

        Label_GuestOrHolding.setText("Guest or Holding:");

        Radiobtn_Guest.setText("Guest");

        Radiobtn_Holding.setText("Holding");

        Label_GuestName.setText("Guest Name:");

        TextBox_GuestName.setText("Guest Name");

        Label_AmountPaid.setText("Amount Paid:");

        TextBox_AmountPaid.setText("0");

        Label_DatePaid.setText("Date Paid:");

        Label_PaymentMethod.setText("Payment Method:");

        Radiobtn_Cash.setText("Cash");

        Radiobtn_Credit.setText("Credit");

        Radiobtn_Other.setText("Other:");

        Btn_Okay.setText("Okay");

        Btn_Cancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_User)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox_User, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_ReservationDate)
                        .addGap(18, 18, 18)
                        .addComponent(TextBox_DateOfReservation))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Label_UseDate)
                            .addComponent(Label_NumberOfNights))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextBox_UseDate)
                            .addComponent(TextBox_NumberOfNights)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_UnitSize)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox_UnitSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_ConfirmationNumber)
                        .addGap(18, 18, 18)
                        .addComponent(TextBox_ConfirmationNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_PointsRequired)
                        .addGap(18, 18, 18)
                        .addComponent(TextBox_PointsRequired))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_PointsAvailable)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_PointsAfter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Label_CalculatedPointsAfter))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_Discounted)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Checkbox_Discounted))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_Upgraded)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Checkbox_upgraded))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_GuestOrHolding)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Radiobtn_Guest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Radiobtn_Holding))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_PaymentMethod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Radiobtn_Credit)
                                    .addComponent(Radiobtn_Cash)
                                    .addComponent(Radiobtn_Other))))
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addComponent(TextBox_OtherPaymentMethod, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_GuestName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextBox_GuestName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_AmountPaid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextBox_AmountPaid))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_DatePaid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextBox_DatePaid)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Okay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Cancel)
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_User))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_PointsAvailable)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ReservationDate)
                    .addComponent(TextBox_DateOfReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_UseDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_NumberOfNights)
                            .addComponent(TextBox_NumberOfNights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(TextBox_UseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_UnitSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_UnitSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ConfirmationNumber)
                    .addComponent(TextBox_ConfirmationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_PointsRequired)
                    .addComponent(TextBox_PointsRequired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_PointsAfter)
                    .addComponent(Label_CalculatedPointsAfter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Discounted)
                    .addComponent(Checkbox_Discounted))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Upgraded)
                    .addComponent(Checkbox_upgraded))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_GuestOrHolding)
                    .addComponent(Radiobtn_Guest)
                    .addComponent(Radiobtn_Holding))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_GuestName)
                    .addComponent(TextBox_GuestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AmountPaid)
                    .addComponent(TextBox_AmountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_DatePaid)
                    .addComponent(TextBox_DatePaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_PaymentMethod)
                    .addComponent(Radiobtn_Cash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radiobtn_Credit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radiobtn_Other)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextBox_OtherPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Okay)
                    .addComponent(Btn_Cancel)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cancel;
    private javax.swing.JButton Btn_Okay;
    private javax.swing.JCheckBox Checkbox_Discounted;
    private javax.swing.JCheckBox Checkbox_upgraded;
    private javax.swing.JComboBox ComboBox_UnitSize;
    private javax.swing.JComboBox ComboBox_User;
    private javax.swing.JLabel Label_AmountPaid;
    private javax.swing.JLabel Label_CalculatedPointsAfter;
    private javax.swing.JLabel Label_ConfirmationNumber;
    private javax.swing.JLabel Label_DatePaid;
    private javax.swing.JLabel Label_Discounted;
    private javax.swing.JLabel Label_GuestName;
    private javax.swing.JLabel Label_GuestOrHolding;
    private javax.swing.JLabel Label_NumberOfNights;
    private javax.swing.JLabel Label_PaymentMethod;
    private javax.swing.JLabel Label_PointsAfter;
    private javax.swing.JLabel Label_PointsAvailable;
    private javax.swing.JLabel Label_PointsRequired;
    private javax.swing.JLabel Label_ReservationDate;
    private javax.swing.JLabel Label_UnitSize;
    private javax.swing.JLabel Label_Upgraded;
    private javax.swing.JLabel Label_UseDate;
    private javax.swing.JLabel Label_User;
    private javax.swing.JRadioButton Radiobtn_Cash;
    private javax.swing.JRadioButton Radiobtn_Credit;
    private javax.swing.JRadioButton Radiobtn_Guest;
    private javax.swing.JRadioButton Radiobtn_Holding;
    private javax.swing.JRadioButton Radiobtn_Other;
    private javax.swing.JTextField TextBox_AmountPaid;
    private javax.swing.JTextField TextBox_ConfirmationNumber;
    private javax.swing.JTextField TextBox_DateOfReservation;
    private javax.swing.JTextField TextBox_DatePaid;
    private javax.swing.JTextField TextBox_GuestName;
    private javax.swing.JTextField TextBox_NumberOfNights;
    private javax.swing.JTextField TextBox_OtherPaymentMethod;
    private javax.swing.JTextField TextBox_PointsRequired;
    private javax.swing.JTextField TextBox_UseDate;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
