/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacationscheduler;

import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;

/**
 *
 * @author erikbenscoter
 */
public class ReservationsTab extends javax.swing.JPanel {

    /**
     * Creates new form ReservationsTab
     */
    ReservationForm newReservation;
    
    public ReservationsTab() {
        initComponents();
        String [] reservationsOptions = {"",
            "View Existing Reservations","Manage Existing Reservation","Make A New Reservation"};
        this.jComboBox1.setModel(new DefaultComboBoxModel(reservationsOptions));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        Panel_ChangePanel = new javax.swing.JPanel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_ChangePanelLayout = new javax.swing.GroupLayout(Panel_ChangePanel);
        Panel_ChangePanel.setLayout(Panel_ChangePanelLayout);
        Panel_ChangePanelLayout.setHorizontalGroup(
            Panel_ChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel_ChangePanelLayout.setVerticalGroup(
            Panel_ChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 372, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Panel_ChangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_ChangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        
        String selection = (String) this.jComboBox1.getSelectedItem();
        this.setVisible(false);
        this.Panel_ChangePanel.setVisible(false);
        
        switch(selection){
            case "Make A New Reservation":
               JFrame jf = new JFrame();
                newReservation = new ReservationForm(jf);
                jf.setSize(600, 700);
                jf.add(newReservation);
                jf.invalidate();
                jf.setVisible(true);
                jf.setAlwaysOnTop(true);
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_ChangePanel;
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables
}
