/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacationscheduler;

import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author erikbenscoter
 */
public class UsersTab extends javax.swing.JPanel {

    /**
     * Creates new form UsersTab
     */
    boolean createNewUser = true;
    UserMaitenanceForm mnuForm;
    UserMaitenanceForm updateUserForm;
    
    public UsersTab() {
        initComponents();
        String [] userComboBoxOptions={"existing user","modify existing user","create a new user"};
        mnuForm = new UserMaitenanceForm();
        updateUserForm = new UserMaitenanceForm();
        
        
        this.UserComboBox.setModel(new DefaultComboBoxModel(userComboBoxOptions));
        
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserComboBox = new javax.swing.JComboBox();
        PanelChanger = new javax.swing.JPanel();

        UserComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        UserComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserComboBoxActionPerformed(evt);
            }
        });

        PanelChanger.setBackground(new java.awt.Color(224, 219, 219));

        javax.swing.GroupLayout PanelChangerLayout = new javax.swing.GroupLayout(PanelChanger);
        PanelChanger.setLayout(PanelChangerLayout);
        PanelChangerLayout.setHorizontalGroup(
            PanelChangerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelChangerLayout.setVerticalGroup(
            PanelChangerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserComboBox, 0, 612, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(PanelChanger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelChanger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UserComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserComboBoxActionPerformed
        String selectedItem = (String) UserComboBox.getSelectedItem();
        PanelChanger.setVisible(false);
        PanelChanger.removeAll();
        this.setVisible(false);
        switch(selectedItem){
            case "create a new user":
                
                PanelChanger.setLayout(new FlowLayout());
                PanelChanger.add(this.mnuForm);
                
               break;
            case "modify existing user":
                
                this.PanelChanger.setLayout(new FlowLayout());
                this.PanelChanger.add(this.updateUserForm);
                break;
            default:
                                       
                break;
        }
        
        PanelChanger.invalidate();
        PanelChanger.setVisible(true);
        this.setVisible(true);
        this.invalidate();
        
    }//GEN-LAST:event_UserComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelChanger;
    private javax.swing.JComboBox UserComboBox;
    // End of variables declaration//GEN-END:variables
}
